export const testimonialsData = [
  {
    id: '1',
    username: '@johnkappa',
    name: 'John Kappa',
    tweet:
      'Here’s an idea 🤔 do something good for someone and don’t post about it on social media.',
    timestamp: '2021-04-21T12:30:00Z',
    source: "<a href='https://twitter.com' target='_blank'>Twitter Web App</a>",
    verified: true,
    profile_link: 'https://x.com/johnkappa',
    profile_image: 'https://i.pravatar.cc/40?u=1',
  },
  {
    id: '2',
    username: '@dailywisdom',
    name: 'Daily Wisdom',
    tweet:
      'The secret to happiness? Focus on what you can control and let go of what you can’t. ✨',
    timestamp: '2022-06-15T08:45:00Z',
    source: "<a href='https://twitter.com' target='_blank'>Twitter Web App</a>",
    verified: false,
    profile_link: 'https://x.com/dailywisdom',
    profile_image: 'https://i.pravatar.cc/40?u=2',
  },
  {
    id: '3',
    username: '@techinsights',
    name: 'Tech Insights',
    tweet: 'AI won’t replace you. But someone who knows how to use AI better than you might. 🤖',
    timestamp: '2023-09-10T14:10:00Z',
    source: "<a href='https://twitter.com' target='_blank'>Twitter Web App</a>",
    verified: true,
    profile_link: 'https://x.com/techinsights',
    profile_image: 'https://i.pravatar.cc/40?u=3',
  },
  {
    id: '4',
    username: '@mindsetcoach',
    name: 'Mindset Coach',
    tweet: 'Success is 1% talent and 99% consistency. Keep going even when no one is watching. 🚀',
    timestamp: '2024-01-05T19:20:00Z',
    source: "<a href='https://twitter.com' target='_blank'>Twitter Web App</a>",
    verified: false,
    profile_link: 'https://x.com/mindsetcoach',
    profile_image: 'https://i.pravatar.cc/40?u=4',
  },
  {
    id: '5',
    username: '@randomfacts',
    name: 'Random Facts',
    tweet: 'Did you know? A group of flamingos is called a ‘flamboyance’. 🦩🔥',
    timestamp: '2024-02-01T10:00:00Z',
    source: "<a href='https://twitter.com' target='_blank'>Twitter Web App</a>",
    verified: true,
    profile_link: 'https://x.com/randomfacts',
    profile_image: 'https://i.pravatar.cc/40?u=5',
  },
];
